INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE, CREATED_AT) VALUES ('JHOJAN', 'MAMANI', 'JAVA', CURRENT_DATE());
INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE, CREATED_AT) VALUES ('PEPE', 'DOE', 'PYTHON', CURRENT_DATE());
INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE, CREATED_AT) VALUES ('JOHN', 'DOW', 'JAVASCRIPT', CURRENT_DATE());
INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE, CREATED_AT) VALUES ('MARIA', 'ROE', 'JAVA', CURRENT_DATE());
INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE, CREATED_AT) VALUES ('PEPE', 'RAE', 'JAVA', CURRENT_DATE());
