INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE) VALUES ('JHOJAN', 'MAMANI', 'JAVA');
INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE) VALUES ('PEPE', 'DOE', 'PYTHON');
INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE) VALUES ('JOHN', 'DOW', 'JAVASCRIPT');
INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE) VALUES ('MARIA', 'ROE', 'JAVA');
INSERT INTO PERSONS (NAME, LAST_NAME, PROGRAMMING_LANGUAGE) VALUES ('PEPE', 'RAE', 'JAVA');
