INSERT INTO CLIENTS(NAME, LASTNAME) VALUES ('Pepe', 'Doe');
INSERT INTO CLIENTS(NAME, LASTNAME) VALUES ('Maria', 'Roe');


INSERT INTO STUDENTS(NAME, LASTNAME) VALUES ('Nacho', 'Goe');
INSERT INTO STUDENTS(NAME, LASTNAME) VALUES ('Pepa', 'Gon');


INSERT INTO COURSES(NAME, INSTRUCTOR) VALUES('Curso de Angular', 'Jhojan');
INSERT INTO COURSES(NAME, INSTRUCTOR) VALUES('Curso de React', 'Midudev');